name: Build and Test
on: [push]
jobs:
  build-rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify package builds
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  test-action:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          file: crates/markdown-extract/CHANGELOG.md
          pattern: "v2.0.0"
