name: Build and Test
on: [push, workflow_dispatch]
jobs:
  build-rust:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify package builds
        run: cargo build --verbose --bin markdown-extract --message-format json --release
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: markdown-extract.exe
          path: D:\a\markdown-extract\markdown-extract\target\release\markdown-extract.exe

  test-action:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          file: crates/markdown-extract/CHANGELOG.md
          pattern: "v2.0.0"
