name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify package builds
        run: cargo build --verbose --bin markdown-extract --message-format json --release
      - name: Run tests
        run: cargo test --verbose

      - name: Calculate SHA256 digest of release artifact
        run: |
          certutil -hashfile D:/a/markdown-extract/markdown-extract/target/release/markdown-extract.exe SHA256
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: D:/a/markdown-extract/markdown-extract/target/release/markdown-extract.exe
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.extract-changelog.outputs.markdown }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
