name: random-testing

on: [workflow_dispatch]

jobs:
  random:
    runs-on: windows-2022
    steps:
      # wget is not available
      # - name: test wget
      #   continue-on-error: true
      #   run: |
      #     wget https://github.com/plutonium-239/markdown-extract/releases/download/v2.1.0/markdown-extract.exe
      - name: test curl
        run: |
          curl -L https://github.com/plutonium-239/markdown-extract/releases/download/v2.1.0/markdown-extract.exe -o markdown-extract.exe
          ls
          curl -L https://github.com/plutonium-239/markdown-extract/raw/refs/heads/master/crates/markdown-extract/CHANGELOG.md -o changelog.md
          
      - name: test markdown-extract
        run: |
          ./markdown-extract.exe "v2.0.0" changelog.md > stdout
          { echo "markdown<<$EOF"; cat stdout; echo "$EOF"; } >> "$GITHUB_OUTPUT"
